site_name: pb-go-api-starter
repo_name: pb-go-api-starter
repo_url: https://github.com/patrickisgreat/pb-go-api-starter
dev_addr: 0.0.0.0:8000
plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - techdocs-core
theme:
  name: material
  logo: images/sc-logo-cloud-white.svg
  features:
    - tabs
