// adapted from common_session.proto for golang.

syntax = "proto3";

import "google/protobuf/wrappers.proto";

option go_package = "github.com/soundcloud/gokit/v2/twirp/common_session";

package proto.patrickisgreat.common.session;

// the geographic location, determined from IP geolocation.
message Geo {
    // two-letter country code, or '--' if unknown
    string country_code = 1;
    google.protobuf.StringValue city = 2;
    google.protobuf.StringValue region = 3;
}

//  Metadata about the interaction between a user and the system
message UserSession {
    // user making the request
    google.protobuf.StringValue user_urn = 1;
    // the property being used for this session
    google.protobuf.StringValue agent_urn = 2;
    // the geographic location of the user
    Geo geo = 3;
    // OAuth scopes for this session
    repeated string scopes = 4;
    // business features that are enabled for this session
    repeated string features = 5;

    // propagate variants for A/B testing
    repeated int32 app_variant_ids = 6;
    // features requested in Firabase A/B tests
    repeated RequestedFeature app_requested_features = 7;
}

message RequestedFeature {
    string name = 1;
    string value = 2;
}