syntax = "proto3";

package proto.patrickisgreat.pb_go_api_starter.api;

option go_package="pb_go_api_starter/api";

import "google/protobuf/wrappers.proto";
import "common_session.proto";

/*
Naming convention for proto rpc, request, and response messages is shown at the top of this post:

https://medium.com/@akhaku/protobuf-definition-best-practices-87f281576f31

with elaboration in points 1 and 3.

RPC + request and response message naming convention:

1) RPC names should always begin with a verb (e.g. Get, List, Create, Update, Delete, Send, Ping, Check).

2) An RPC called DoFoo should have this definition in proto IDL:

  rpc DoFoo (DoFooRequest) returns (DoFooResponse) {}
*/


message GetCookieRequest {
  // The session of the user requesting a fortune.
  proto.patrickisgreat.common.session.UserSession user_session = 1;
}

message GetCookieResponse {
    /* A random fortune cookie message from fortune.txt */
    string fortune_cookie_message = 1; // Note: always return a fortune cookie message, so no string wrapper type needed
}


message GetCookieFlakyRequest {
    // The session of the user requesting a fortune.
    proto.patrickisgreat.common.session.UserSession user_session = 1;
    /* Setting to true causes the request to fail for sure (i.e., not to just randomly fail) */
    bool fail = 2;
}

message GetCookieFlakyResponse {
    /* A random fortune cookie message from fortune.txt */
    string fortune_cookie_message = 1;
}


message GetCookieLateRequest {
    // The session of the user requesting a fortune.
    proto.patrickisgreat.common.session.UserSession user_session = 1;
    /* Number of milliseconds to wait before returning the response */
    google.protobuf.Int32Value delay_ms = 2;
}

message GetCookieLateResponse {
    /* A random fortune cookie message from fortune.txt */
    string fortune_cookie_message = 1;
}

service Fortune {
    /* Get a random fortune cookie message from fortune.txt */
    rpc GetCookie (GetCookieRequest) returns (GetCookieResponse) {
    }

    /* Get a random fortune cookie message from fortune.txt. Sometimes this fails. */
    rpc GetCookieFlaky (GetCookieFlakyRequest) returns (GetCookieFlakyResponse) {
    }

    /* Get a random fortune cookie message from fortune.txt, after the specified delay. */
    rpc GetCookieLate (GetCookieLateRequest) returns (GetCookieLateResponse) {
    }
}
